version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  kafka1:
    image: domacker/kafka_with_prometheus:7.8.0
    hostname: kafka1
    container_name: kafka1
    #healthcheck:
    #  test: ['CMD', 'curl http://localhost:8090']
    #  interval: 1m30s
    #  timeout: 30s
    #  retries: 5
    #  start_period: 30s
    ports:
      - '9092:9092'
      - '9093:9093'
      - '8090:8090'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_OPTS: '-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.3.1.jar=8090:/opt/prometheus/kafka-0-8-2.yml'
    volumes:
      - ./kafka1/data:/var/lib/kafka/data
    #networks:
    #  - kafka-net

  kafka2:
    image: domacker/kafka_with_prometheus:7.8.0
    hostname: kafka2
    container_name: kafka2
    #healthcheck:
    #  test: ['CMD', 'curl http://localhost:8091']
    #  interval: 1m30s
    #  timeout: 30s
    #  retries: 5
    #  start_period: 30s
    ports:
      - '9094:9092'
      - '9095:9093'
      - '8091:8091'
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_OPTS: '-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.3.1.jar=8091:/opt/prometheus/kafka-0-8-2.yml'
    volumes:
      - ./kafka2/data:/var/lib/kafka/data
    #networks:
    #  - kafka-net

  kafka3:
    image: domacker/kafka_with_prometheus:7.8.0
    hostname: kafka3
    container_name: kafka3
    #healthcheck:
    #  test: ['CMD', 'curl http://localhost:8092']
    #  interval: 1m30s
    #  timeout: 30s
    #  retries: 5
    #  start_period: 30s
    ports:
      - '9096:9092'
      - '9097:9093'
      - '8092:8092'
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka3:9092,CONTROLLER://kafka3:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_OPTS: '-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.3.1.jar=8092:/opt/prometheus/kafka-0-8-2.yml'
    volumes:
      - ./kafka3/data:/var/lib/kafka/data
    #networks:
    #  - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    #healthcheck:
    #  test: ['CMD', 'nc -z localhost 8080']
    #  interval: 1m30s
    #  timeout: 30s
    #  retries: 5
    #  start_period: 30s
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    #networks:
    #  - kafka-net

  prometheus:
    image: prom/prometheus
    #healthcheck:
    #  test: ['CMD', 'nc -z localhost 9090']
    #  interval: 1m30s
    #  timeout: 30s
    #  retries: 5
    #  start_period: 30s
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka-ui
    #networks:
    #  - kafka-net

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    #healthcheck:
    #  test: ['CMD', 'nc -z localhost 3000']
    #  interval: 1m30s
    #  timeout: 30s
    #  retries: 5
    #  start_period: 30s
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    #networks:
    #  - kafka-net
